easy tests

diff --git a/lexer/Makefile b/lexer/Makefile
--- a/lexer/Makefile
+++ b/lexer/Makefile
@@ -1,4 +1,24 @@
-run:
+FILES := $(wildcard ${FOLDER}/*)
+RED := \033[0;31m
+GREEN := \033[0;32m
+RESET := \033[0m
+
+run: compileS
+	./lexer ${FILE}
+
+test: compile ${FILES}
+	@for file in $(FILES); do \
+		echo "Processing $$file" && ./lexer $$file; \
+		if [ $$? = 0 ]; then \
+            echo "${GREEN}Test Passed${RESET}"; \
+			echo "-----------------------------------"; \
+        else \
+            echo "${RED}Test Failed${RESET}"; \
+			echo "-----------------------------------"; \
+        fi \
+	done
+
+compile:
 	lex lex.l
 	gcc lex.yy.c -o lexer
-	./lexer ${FILE}
+
